### PR TITLE
Create template solution

### LINKED ISSUE #1: Create template solution file

### PR DESCRIPTION
**Pull request by michaelhoehn**
does not compile

### Issues addressed by this PR

Closes #1 

### Test files

Pull the code, have a look, and test by rebuilding and verifying project references and any errors in the log.

### CODE REVIEW

**Comment by michaelhoehn** [comment]
@kayleighhoude this is ready for your review. After this is merged you can begin to populate the toolkit repo with new issues and features.

**Comment by michaelhoehn** [comment]
@BHoMBot check compliance

**Comment by michaelhoehn** [comment]
@BHoMBot check compliance

**Comment by michaelhoehn** [comment]
@BHoMBot check compliance

**Comment by michaelhoehn** [comment]
@BHoMBot check compliance

**Review by kayleighhoude — APPROVED** [review]
Happy with this, let's get this merged so we can start object creation!

**Pull request merged**
