### PR TITLE
EmbodiedSuffering_Toolkit-Updated Materials and Updated Datasets

### PR DESCRIPTION
**Pull request by kayleighhoude**
### Issues addressed by this PR

Closes #

### CODE REVIEW

**Comment by kayleighhoude** [comment]
image

Enum Updated
Datasets created and reviewed against engine methods

@michaelhoehn ready for your review!

**Review by michaelhoehn — APPROVED** [review]
Datasets looks good. Happy to merge.

**Comment by michaelhoehn** [comment]
@BHoMBot check required

**Comment by michaelhoehn** [comment]
@BHoMBot check ready-to-merge

**Comment by kayleighhoude** [comment]
@adecler this has been merged (new datasets and an updated materials enum!)

**Comment by adecler** [comment]
Thanks @kayleighhoude, I have pushed the changes to the website.

Just be mindful that Recycled steel currently has a total ration above 100%

image

**Pull request merged**
