### PR TITLE
Materials Enum and Material Import Datasets

### LINKED ISSUE #38: Gypsum Import By Cost dataset has all countries marked as undefined
#### Description:
See title and image below

#### Steps to reproduce:
image

### PR DESCRIPTION
**Pull request by kayleighhoude**
### Issues addressed by this PR

Closes #38, 36

### Test files
Original Data in Excel:
https://kierantimberlakeassociates.sharepoint.com/sites/ForcedLaborModernSlaveryCalculator?e=1%3A8dc63284bb804159a8fe534bfd39d610

Grasshopper Script with Datasets Rendered: 
https://kierantimberlakeassociates.sharepoint.com/sites/ForcedLaborModernSlaveryCalculator?e=1%3A8dc63284bb804159a8fe534bfd39d610

### CODE REVIEW

**Comment by kayleighhoude** [comment]
image

Ready for final review! @michaelhoehn

**Comment by kayleighhoude** [comment]
@adecler once this is merged we will have material import datasets for:

Aluminium
Asphalt
Brick
Carpet
Cobalt
Glass
Gypsum (updated material value)
PVC
Timber
Zinc

**Comment by kayleighhoude** [comment]
@michaelhoehn test file with engine method tests:
image

**Review by michaelhoehn — APPROVED** [review]
Looks great and works with the current eval methods as expected. Thanks @kayleighhoude!

**Comment by michaelhoehn** [comment]
@BHoMBot required

**Comment by michaelhoehn** [comment]
@BHoMBot check required

**Comment by adecler** [comment]
@BHoMBot check compliance
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core
@BHoMBot check null-handling
@BHoMBot check serialisation
@BHoMBot check ready-to-merge

**Pull request merged**
